export const FIGMA_FILE_KEY = '735drrzVTmf4AhQJwQe6vX';
export const FIGMA_PAGE_ID = '0:1';
export const SLIDE_WIDTH = 1920;
export const SLIDE_HEIGHT = 1080;
export const PILOT_START_X = 13050;
export const PILOT_START_Y = 119;
export const PILOT_GAP_Y = 140;

export const palette = {
  bg: '#0C0C0F',
  black: '#000000',
  white: '#FFFFFF',
  secondaryText: 'rgba(255,255,255,0.55)',
  mutedText: 'rgba(255,255,255,0.38)',
  card: 'rgba(255,255,255,0.055)',
  cardStrong: 'rgba(255,255,255,0.08)',
  cardBorder: 'rgba(255,255,255,0.12)',
  red: '#EB2516',
  redBright: '#FF2A1C',
  orange: '#FF6A00',
  deepRed: '#5A0908',
  amber: '#FF9A3D'
};

export function stringifyForCode(value) {
  return JSON.stringify(value, null, 2);
}

export function buildGeneratedFileHeader() {
  return [
    '// Generated by src/figma/print-create-pilot-script.mjs',
    '// Run this file through ChatGPT/Figma MCP use_figma.',
    '// Design priority: DESIGN_FIDELITY_ADDENDUM.md > MASTER_CODEX_PROMPT.md',
    ''
  ].join('\n');
}

export function buildFigmaScript(deckData) {
  const serializedDeck = stringifyForCode(deckData);
  const serializedPalette = stringifyForCode(palette);

  return `${buildGeneratedFileHeader()}const deckData = ${serializedDeck};
const palette = ${serializedPalette};

const SLIDE_WIDTH = ${SLIDE_WIDTH};
const SLIDE_HEIGHT = ${SLIDE_HEIGHT};
const PILOT_START_X = ${PILOT_START_X};
const PILOT_START_Y = ${PILOT_START_Y};
const PILOT_GAP_Y = ${PILOT_GAP_Y};

const page = figma.root.children.find((p) => p.id === '${FIGMA_PAGE_ID}' || p.name === 'Page 1');
if (!page) {
  throw new Error('Target Figma page 0:1 / Page 1 not found.');
}

await figma.setCurrentPageAsync(page);
const availableFonts = await figma.listAvailableFontsAsync();
const loadedFonts = new Set();
const createdNodeIds = [];

function rgb(value) {
  return {
    r: value[0] / 255,
    g: value[1] / 255,
    b: value[2] / 255
  };
}

function solid(rgbValue, opacity = 1) {
  return {
    type: 'SOLID',
    color: rgbValue,
    opacity
  };
}

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  const chunk = normalized.length === 3
    ? normalized.split('').map((char) => char + char).join('')
    : normalized;
  return rgb([
    parseInt(chunk.slice(0, 2), 16),
    parseInt(chunk.slice(2, 4), 16),
    parseInt(chunk.slice(4, 6), 16)
  ]);
}

function rgbaStringToPaint(value) {
  const match = value.match(/rgba\\((\\d+),(\\d+),(\\d+),(\\d*\\.?\\d+)\\)/);
  if (!match) {
    throw new Error('Unsupported rgba string: ' + value);
  }
  return solid(rgb([Number(match[1]), Number(match[2]), Number(match[3])]), Number(match[4]));
}

function paintFromToken(value) {
  if (value.startsWith('#')) {
    return solid(hexToRgb(value), 1);
  }
  if (value.startsWith('rgba')) {
    return rgbaStringToPaint(value);
  }
  throw new Error('Unsupported paint token: ' + value);
}

function findFont(candidates) {
  for (const candidate of candidates) {
    const match = availableFonts.find((entry) =>
      entry.fontName.family === candidate.family && entry.fontName.style === candidate.style
    );
    if (match) {
      return match.fontName;
    }
  }

  const inter = availableFonts.find((entry) => entry.fontName.family === 'Inter');
  if (inter) {
    return inter.fontName;
  }

  throw new Error('Neither X5 Sans nor Inter is available in this file.');
}

async function ensureFont(fontName) {
  const key = \`\${fontName.family}__\${fontName.style}\`;
  if (!loadedFonts.has(key)) {
    await figma.loadFontAsync(fontName);
    loadedFonts.add(key);
  }
}

const FONT_BODY = findFont([
  { family: 'X5 Sans', style: 'Regular' },
  { family: 'X5 Sans', style: 'Book' },
  { family: 'Inter', style: 'Regular' }
]);
const FONT_MEDIUM = findFont([
  { family: 'X5 Sans', style: 'Medium' },
  { family: 'X5 Sans', style: 'DemiBold' },
  { family: 'Inter', style: 'Medium' },
  { family: 'Inter', style: 'Semi Bold' }
]);
const FONT_BOLD = findFont([
  { family: 'X5 Sans', style: 'Bold' },
  { family: 'X5 Sans', style: 'Heavy' },
  { family: 'Inter', style: 'Bold' }
]);

function register(node) {
  createdNodeIds.push(node.id);
  return node;
}

function setNodeFills(node, fills) {
  node.fills = fills;
  return node;
}

function setNodeStrokes(node, strokes, strokeWeight = 1) {
  node.strokes = strokes;
  node.strokeWeight = strokeWeight;
  return node;
}

function addFrameBase(spec, index) {
  const frame = register(figma.createFrame());
  frame.name = spec.frameName;
  frame.resize(SLIDE_WIDTH, SLIDE_HEIGHT);
  frame.x = PILOT_START_X;
  frame.y = PILOT_START_Y + index * (SLIDE_HEIGHT + PILOT_GAP_Y);
  frame.clipsContent = false;
  frame.cornerRadius = 0;
  setNodeFills(frame, [paintFromToken(palette.bg)]);
  figma.currentPage.appendChild(frame);
  return frame;
}

function addGlow(frame, options) {
  const ellipse = register(figma.createEllipse());
  ellipse.resize(options.width, options.height);
  ellipse.x = options.x;
  ellipse.y = options.y;
  ellipse.opacity = options.opacity ?? 0.9;
  ellipse.blendMode = 'SCREEN';
  ellipse.effects = [{
    type: 'LAYER_BLUR',
    radius: options.blur ?? 180,
    visible: true
  }];
  ellipse.fills = [{
    type: 'GRADIENT_RADIAL',
    gradientStops: [
      { position: 0, color: { ...hexToRgb(options.inner), a: options.innerAlpha ?? 0.9 } },
      { position: 1, color: { ...hexToRgb(options.outer), a: 0 } }
    ],
    gradientTransform: [[1, 0, 0], [0, 1, 0]]
  }];
  frame.appendChild(ellipse);
  return ellipse;
}

function addLine(frame, { x, y, width, height = 2, color = palette.red, opacity = 1, radius = 999 }) {
  const rect = register(figma.createRectangle());
  rect.resize(width, height);
  rect.x = x;
  rect.y = y;
  rect.cornerRadius = radius;
  rect.fills = [paintFromToken(color)];
  rect.opacity = opacity;
  frame.appendChild(rect);
  return rect;
}

async function addText(frame, options) {
  const text = register(figma.createText());
  frame.appendChild(text);
  const fontName = options.fontRole === 'bold'
    ? FONT_BOLD
    : options.fontRole === 'medium'
      ? FONT_MEDIUM
      : FONT_BODY;
  await ensureFont(fontName);
  text.fontName = fontName;
  text.fontSize = options.fontSize;
  text.lineHeight = { unit: 'PIXELS', value: options.lineHeight ?? Math.round(options.fontSize * 1.12) };
  text.letterSpacing = { unit: 'PIXELS', value: options.letterSpacing ?? 0 };
  text.characters = options.text;
  text.x = options.x;
  text.y = options.y;
  text.resize(options.width ?? text.width, options.height ?? text.height);
  text.textAlignHorizontal = options.align ?? 'LEFT';
  text.textAutoResize = options.autoResize ?? 'HEIGHT';
  text.fills = [paintFromToken(options.color ?? palette.white)];
  if (options.opacity != null) {
    text.opacity = options.opacity;
  }
  return text;
}

function addGlassCard(frame, options) {
  const card = register(figma.createFrame());
  card.name = options.name ?? 'Card';
  card.resize(options.width, options.height);
  card.x = options.x;
  card.y = options.y;
  card.cornerRadius = options.cornerRadius ?? 32;
  card.clipsContent = true;
  card.fills = [paintFromToken(options.fill ?? palette.card)];
  card.strokes = [paintFromToken(options.stroke ?? palette.cardBorder)];
  card.strokeWeight = options.strokeWeight ?? 1;
  frame.appendChild(card);

  const innerGlow = register(figma.createRectangle());
  innerGlow.resize(options.width, Math.max(100, Math.round(options.height * 0.35)));
  innerGlow.x = 0;
  innerGlow.y = 0;
  innerGlow.cornerRadius = card.cornerRadius;
  innerGlow.fills = [{
    type: 'GRADIENT_LINEAR',
    gradientStops: [
      { position: 0, color: { ...hexToRgb(options.glow ?? palette.red), a: options.glowOpacity ?? 0.18 } },
      { position: 1, color: { ...hexToRgb(options.glow ?? palette.red), a: 0 } }
    ],
    gradientTransform: [[1, 0, 0], [0, 1, 0]]
  }];
  card.appendChild(innerGlow);

  return card;
}

async function addBulletColumn(card, bullets, options = {}) {
  const list = register(figma.createFrame());
  card.appendChild(list);
  list.name = options.name ?? 'Bullet Column';
  list.x = options.x ?? 36;
  list.y = options.y ?? 36;
  list.resize(options.width ?? card.width - 72, options.height ?? card.height - 72);
  list.layoutMode = 'VERTICAL';
  list.primaryAxisSizingMode = 'AUTO';
  list.counterAxisSizingMode = 'FIXED';
  list.itemSpacing = options.itemSpacing ?? 20;
  list.fills = [];
  list.strokes = [];

  for (const bullet of bullets) {
    const row = register(figma.createFrame());
    row.name = 'Bullet Row';
    row.layoutMode = 'HORIZONTAL';
    row.primaryAxisSizingMode = 'AUTO';
    row.counterAxisSizingMode = 'AUTO';
    row.itemSpacing = 14;
    row.fills = [];
    row.strokes = [];
    list.appendChild(row);

    const dot = register(figma.createEllipse());
    dot.resize(10, 10);
    dot.fills = [paintFromToken(options.dotColor ?? palette.redBright)];
    row.appendChild(dot);

    const text = register(figma.createText());
    row.appendChild(text);
    await ensureFont(FONT_BODY);
    text.fontName = FONT_BODY;
    text.fontSize = options.fontSize ?? 24;
    text.lineHeight = { unit: 'PIXELS', value: options.lineHeight ?? 32 };
    text.characters = bullet;
    text.fills = [paintFromToken(options.color ?? palette.white)];
    text.layoutSizingHorizontal = 'FILL';
    text.textAutoResize = 'HEIGHT';
    text.resize(options.textWidth ?? list.width - 40, text.height);
  }

  return list;
}

async function renderCover(frame, spec) {
  addGlow(frame, { x: 590, y: 650, width: 740, height: 300, inner: palette.redBright, outer: palette.orange, blur: 220, innerAlpha: 0.9 });
  addGlow(frame, { x: 330, y: 720, width: 1260, height: 180, inner: palette.orange, outer: palette.red, blur: 240, innerAlpha: 0.55, opacity: 0.8 });
  addLine(frame, { x: 120, y: 118, width: 1680, height: 1, color: palette.cardBorder, opacity: 0.35, radius: 1 });

  await addText(frame, {
    x: 560,
    y: 104,
    width: 800,
    text: spec.eyebrow,
    fontSize: 24,
    letterSpacing: 1.8,
    fontRole: 'medium',
    align: 'CENTER',
    color: palette.secondaryText
  });

  await addText(frame, {
    x: 300,
    y: 340,
    width: 1320,
    text: spec.title,
    fontSize: 112,
    lineHeight: 114,
    fontRole: 'bold',
    align: 'CENTER'
  });

  await addText(frame, {
    x: 360,
    y: 720,
    width: 1200,
    text: spec.subtitle,
    fontSize: 28,
    lineHeight: 40,
    fontRole: 'body',
    align: 'CENTER',
    color: palette.secondaryText
  });

  await addText(frame, {
    x: 760,
    y: 904,
    width: 400,
    text: spec.footer,
    fontSize: 24,
    fontRole: 'medium',
    align: 'CENTER',
    color: palette.white
  });

  addLine(frame, { x: 736, y: 948, width: 448, height: 3, color: palette.redBright, opacity: 0.95 });
}

async function renderProblem(frame, spec) {
  addGlow(frame, { x: 1170, y: 48, width: 540, height: 240, inner: palette.redBright, outer: palette.orange, blur: 200, innerAlpha: 0.35, opacity: 0.7 });
  await addText(frame, { x: 96, y: 82, width: 980, text: spec.title, fontSize: 48, lineHeight: 56, fontRole: 'bold' });
  await addText(frame, { x: 96, y: 154, width: 1040, text: spec.message, fontSize: 26, lineHeight: 36, color: palette.secondaryText });

  const anchor = addGlassCard(frame, { x: 96, y: 250, width: 560, height: 580, fill: palette.cardStrong, glow: palette.red });
  await addText(anchor, { x: 36, y: 40, width: 420, text: 'Операционное трение', fontSize: 22, fontRole: 'medium', color: palette.secondaryText });
  await addText(anchor, { x: 36, y: 86, width: 440, text: '73%', fontSize: 120, lineHeight: 110, fontRole: 'bold', color: palette.redBright });
  await addText(anchor, { x: 36, y: 220, width: 470, text: 'рабочего времени не имеет цифрового следа в системах компании', fontSize: 34, lineHeight: 42, fontRole: 'medium' });
  await addBulletColumn(anchor, spec.content.slice(0, 3), { x: 36, y: 360, width: 480, fontSize: 24, lineHeight: 32 });

  const cardPositions = [
    { x: 708, y: 250, width: 510, height: 220, glow: palette.orange },
    { x: 1248, y: 250, width: 576, height: 220, glow: palette.redBright },
    { x: 708, y: 502, width: 360, height: 278, glow: palette.red },
    { x: 1098, y: 502, width: 360, height: 278, glow: palette.orange },
    { x: 1488, y: 502, width: 336, height: 278, glow: palette.redBright }
  ];

  for (let index = 0; index < cardPositions.length; index += 1) {
    const item = spec.content[index + 1] ?? spec.content[index] ?? '';
    const card = addGlassCard(frame, { ...cardPositions[index], fill: palette.card, stroke: palette.cardBorder, glow: cardPositions[index].glow });
    await addText(card, { x: 28, y: 28, width: card.width - 56, text: String(index + 2).padStart(2, '0'), fontSize: 18, fontRole: 'medium', color: palette.secondaryText });
    await addText(card, { x: 28, y: 68, width: card.width - 56, text: item, fontSize: 27, lineHeight: 34, fontRole: 'medium' });
  }

  addLine(frame, { x: 658, y: 418, width: 36, height: 2, color: palette.redBright });
  addLine(frame, { x: 658, y: 622, width: 36, height: 2, color: palette.redBright });
}

async function renderTargetState(frame, spec) {
  addGlow(frame, { x: 1180, y: 54, width: 420, height: 220, inner: palette.redBright, outer: palette.orange, blur: 200, innerAlpha: 0.4, opacity: 0.65 });
  await addText(frame, { x: 96, y: 86, width: 980, text: spec.title, fontSize: 48, lineHeight: 56, fontRole: 'bold' });
  await addText(frame, { x: 96, y: 158, width: 1040, text: spec.message, fontSize: 26, lineHeight: 36, color: palette.secondaryText });
  addLine(frame, { x: 164, y: 348, width: 1540, height: 4, color: palette.redBright, opacity: 0.9 });

  const cardWidth = 512;
  const xPositions = [96, 704, 1312];

  for (let index = 0; index < spec.pillars.length; index += 1) {
    const pillar = spec.pillars[index];
    const card = addGlassCard(frame, {
      x: xPositions[index],
      y: 400,
      width: cardWidth,
      height: 458,
      fill: index === 1 ? palette.cardStrong : palette.card,
      glow: index === 1 ? palette.orange : palette.red
    });
    await addText(card, { x: 34, y: 34, width: 200, text: \`0\${index + 1}\`, fontSize: 18, fontRole: 'medium', color: palette.secondaryText });
    await addText(card, { x: 34, y: 74, width: 420, text: pillar.title, fontSize: 32, lineHeight: 38, fontRole: 'bold' });
    await addText(card, { x: 34, y: 166, width: 430, text: pillar.body, fontSize: 24, lineHeight: 34, color: palette.secondaryText });
    addLine(card, { x: 34, y: 136, width: 120, height: 3, color: index === 1 ? palette.orange : palette.redBright });
  }
}

async function renderSolution(frame, spec) {
  addGlow(frame, { x: 1340, y: 36, width: 420, height: 220, inner: palette.redBright, outer: palette.orange, blur: 220, innerAlpha: 0.4, opacity: 0.7 });
  await addText(frame, { x: 96, y: 84, width: 940, text: spec.title, fontSize: 48, lineHeight: 56, fontRole: 'bold' });
  await addText(frame, { x: 96, y: 156, width: 1040, text: spec.message, fontSize: 26, lineHeight: 36, color: palette.secondaryText });

  const engine = addGlassCard(frame, { x: 96, y: 252, width: 1728, height: 316, fill: palette.cardStrong, glow: palette.red });
  addLine(engine, { x: 98, y: 158, width: 1528, height: 3, color: palette.redBright, opacity: 0.95 });

  const stepWidth = 240;
  for (let index = 0; index < spec.loopSteps.length; index += 1) {
    const x = 48 + index * 276;
    const chip = addGlassCard(engine, { x, y: 78, width: stepWidth, height: 160, fill: palette.card, stroke: palette.cardBorder, glow: index % 2 === 0 ? palette.orange : palette.red });
    await addText(chip, { x: 24, y: 22, width: 80, text: \`0\${index + 1}\`, fontSize: 18, fontRole: 'medium', color: palette.secondaryText });
    await addText(chip, { x: 24, y: 58, width: 184, text: spec.loopSteps[index], fontSize: 26, lineHeight: 30, fontRole: 'medium' });
  }

  const notes = addGlassCard(frame, { x: 96, y: 620, width: 1728, height: 276, fill: palette.card, glow: palette.orange });
  await addBulletColumn(notes, spec.content, { x: 36, y: 36, width: 700, fontSize: 24, lineHeight: 32 });
  await addText(notes, { x: 920, y: 48, width: 700, text: 'Executive operating loop, not UX flowchart', fontSize: 24, fontRole: 'medium', color: palette.secondaryText });
  await addText(notes, { x: 920, y: 98, width: 700, text: 'Система должна принимать сигналы бизнеса, переводить их в задачу, фиксировать исполнение и возвращать метрики в контур управления.', fontSize: 28, lineHeight: 38, fontRole: 'medium' });
}

async function renderMetrics(frame, spec) {
  addGlow(frame, { x: 1220, y: 38, width: 470, height: 230, inner: palette.redBright, outer: palette.orange, blur: 210, innerAlpha: 0.38, opacity: 0.68 });
  await addText(frame, { x: 96, y: 84, width: 980, text: spec.title, fontSize: 48, lineHeight: 56, fontRole: 'bold' });
  await addText(frame, { x: 96, y: 156, width: 1020, text: spec.message, fontSize: 26, lineHeight: 36, color: palette.secondaryText });

  const left = addGlassCard(frame, { x: 96, y: 250, width: 872, height: 612, fill: palette.cardStrong, glow: palette.redBright });
  await addText(left, { x: 44, y: 42, width: 520, text: spec.metrics[0].label, fontSize: 28, lineHeight: 34, fontRole: 'medium', color: palette.secondaryText });
  await addText(left, { x: 44, y: 118, width: 520, text: spec.metrics[0].value, fontSize: 166, lineHeight: 150, fontRole: 'bold', color: palette.redBright });
  await addText(left, { x: 44, y: 314, width: 560, text: spec.metrics[0].note, fontSize: 34, lineHeight: 42, fontRole: 'medium' });
  addLine(left, { x: 44, y: 276, width: 310, height: 4, color: palette.orange, opacity: 0.9 });

  const topRight = addGlassCard(frame, { x: 1012, y: 250, width: 812, height: 284, fill: palette.card, glow: palette.orange });
  await addText(topRight, { x: 36, y: 36, width: 420, text: spec.metrics[1].label, fontSize: 26, lineHeight: 34, fontRole: 'medium', color: palette.secondaryText });
  await addText(topRight, { x: 36, y: 96, width: 340, text: spec.metrics[1].value, fontSize: 108, lineHeight: 104, fontRole: 'bold', color: palette.orange });
  await addText(topRight, { x: 412, y: 118, width: 340, text: spec.metrics[1].note, fontSize: 24, lineHeight: 32, color: palette.white });

  const bottomRight = addGlassCard(frame, { x: 1012, y: 578, width: 812, height: 284, fill: palette.card, glow: palette.red });
  await addText(bottomRight, { x: 36, y: 36, width: 420, text: spec.metrics[2].label, fontSize: 26, lineHeight: 34, fontRole: 'medium', color: palette.secondaryText });
  await addText(bottomRight, { x: 36, y: 96, width: 340, text: spec.metrics[2].value, fontSize: 108, lineHeight: 104, fontRole: 'bold', color: palette.redBright });
  await addText(bottomRight, { x: 412, y: 118, width: 340, text: spec.metrics[2].note, fontSize: 24, lineHeight: 32, color: palette.white });

  await addText(frame, { x: 96, y: 920, width: 920, text: spec.footnote, fontSize: 20, lineHeight: 28, color: palette.mutedText });
}

async function renderRoadmap(frame, spec) {
  addGlow(frame, { x: 1240, y: 40, width: 460, height: 220, inner: palette.redBright, outer: palette.orange, blur: 210, innerAlpha: 0.38, opacity: 0.7 });
  await addText(frame, { x: 96, y: 84, width: 940, text: spec.title, fontSize: 48, lineHeight: 56, fontRole: 'bold' });
  await addText(frame, { x: 96, y: 156, width: 1020, text: spec.message, fontSize: 26, lineHeight: 36, color: palette.secondaryText });
  addLine(frame, { x: 168, y: 612, width: 1488, height: 5, color: palette.redBright, opacity: 0.9 });

  const positions = [124, 668, 1212];
  for (let index = 0; index < spec.milestones.length; index += 1) {
    const step = spec.milestones[index];
    const card = addGlassCard(frame, { x: positions[index], y: 322, width: 496, height: 360, fill: index === 2 ? palette.cardStrong : palette.card, glow: index === 1 ? palette.orange : palette.red });
    await addText(card, { x: 36, y: 36, width: 220, text: step.year, fontSize: 88, lineHeight: 84, fontRole: 'bold', color: index === 1 ? palette.orange : palette.redBright });
    await addText(card, { x: 36, y: 154, width: 400, text: step.title, fontSize: 32, lineHeight: 38, fontRole: 'medium' });
    await addText(card, { x: 36, y: 236, width: 404, text: step.body, fontSize: 24, lineHeight: 32, color: palette.secondaryText });
  }

  await addText(frame, { x: 96, y: 820, width: 980, text: 'Pilot → territory → network scale. Composition borrows annual progression logic from the source deck instead of inventing a generic PM roadmap.', fontSize: 24, lineHeight: 34, color: palette.secondaryText });
}

for (let index = 0; index < deckData.slides.length; index += 1) {
  const spec = deckData.slides[index];
  const frame = addFrameBase(spec, index);
  if (spec.patternId === 'hero_product_initiative_cover') {
    await renderCover(frame, spec);
  } else if (spec.patternId === 'problem_friction_map') {
    await renderProblem(frame, spec);
  } else if (spec.patternId === 'target_state_outcome_pillars') {
    await renderTargetState(frame, spec);
  } else if (spec.patternId === 'solution_engine_operating_loop') {
    await renderSolution(frame, spec);
  } else if (spec.patternId === 'business_effect_metric_cards') {
    await renderMetrics(frame, spec);
  } else if (spec.patternId === 'pilot_to_scale_roadmap') {
    await renderRoadmap(frame, spec);
  } else {
    throw new Error('Unsupported pattern: ' + spec.patternId);
  }
}

return {
  createdNodeIds,
  frameNames: deckData.slides.map((slide) => slide.frameName),
  fileKey: '${FIGMA_FILE_KEY}',
  pageId: '${FIGMA_PAGE_ID}',
  instruction: 'Run output/figma-create-pilot.generated.js through ChatGPT/Figma MCP use_figma.'
};`;
}
